"use client"

import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge, ChevronRight, Globe, MapPin, Search, X } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import React, { useState } from 'react'

const regions = [
  'Бүгд',
  'Asia',
  'Europe',
  'North America',
  'South America',
  'Africa',
  'Oceania',
  'Middle East',
];

const countries = [
    {
      id: 'AF',
      name: 'Afghanistan',
      code: 'AF',
      img: 'https://flagcdn.com/w320/af.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AL',
      name: 'Albania',
      code: 'AL',
      img: 'https://flagcdn.com/w320/al.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'DZ',
      name: 'Algeria',
      code: 'DZ',
      img: 'https://flagcdn.com/w320/dz.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AS',
      name: 'American Samoa',
      code: 'AS',
      img: 'https://flagcdn.com/w320/as.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AD',
      name: 'Andorra',
      code: 'AD',
      img: 'https://flagcdn.com/w320/ad.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AO',
      name: 'Angola',
      code: 'AO',
      img: 'https://flagcdn.com/w320/ao.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AI',
      name: 'Anguilla',
      code: 'AI',
      img: 'https://flagcdn.com/w320/ai.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AQ',
      name: 'Antarctica',
      code: 'AQ',
      img: 'https://flagcdn.com/w320/aq.png',
      region: 'Antarctica',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AG',
      name: 'Antigua and Barbuda',
      code: 'AG',
      img: 'https://flagcdn.com/w320/ag.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AR',
      name: 'Argentina',
      code: 'AR',
      img: 'https://flagcdn.com/w320/ar.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AM',
      name: 'Armenia',
      code: 'AM',
      img: 'https://flagcdn.com/w320/am.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AW',
      name: 'Aruba',
      code: 'AW',
      img: 'https://flagcdn.com/w320/aw.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AU',
      name: 'Australia',
      code: 'AU',
      img: 'https://flagcdn.com/w320/au.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AT',
      name: 'Austria',
      code: 'AT',
      img: 'https://flagcdn.com/w320/at.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AZ',
      name: 'Azerbaijan',
      code: 'AZ',
      img: 'https://flagcdn.com/w320/az.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BS',
      name: 'Bahamas',
      code: 'BS',
      img: 'https://flagcdn.com/w320/bs.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BH',
      name: 'Bahrain',
      code: 'BH',
      img: 'https://flagcdn.com/w320/bh.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BD',
      name: 'Bangladesh',
      code: 'BD',
      img: 'https://flagcdn.com/w320/bd.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BB',
      name: 'Barbados',
      code: 'BB',
      img: 'https://flagcdn.com/w320/bb.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BY',
      name: 'Belarus',
      code: 'BY',
      img: 'https://flagcdn.com/w320/by.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BE',
      name: 'Belgium',
      code: 'BE',
      img: 'https://flagcdn.com/w320/be.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BZ',
      name: 'Belize',
      code: 'BZ',
      img: 'https://flagcdn.com/w320/bz.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BJ',
      name: 'Benin',
      code: 'BJ',
      img: 'https://flagcdn.com/w320/bj.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BM',
      name: 'Bermuda',
      code: 'BM',
      img: 'https://flagcdn.com/w320/bm.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BT',
      name: 'Bhutan',
      code: 'BT',
      img: 'https://flagcdn.com/w320/bt.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BO',
      name: 'Bolivia',
      code: 'BO',
      img: 'https://flagcdn.com/w320/bo.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BQ',
      name: 'Bonaire',
      code: 'BQ',
      img: 'https://flagcdn.com/w320/bq.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BA',
      name: 'Bosnia and Herzegovina',
      code: 'BA',
      img: 'https://flagcdn.com/w320/ba.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BW',
      name: 'Botswana',
      code: 'BW',
      img: 'https://flagcdn.com/w320/bw.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BV',
      name: 'Bouvet Island',
      code: 'BV',
      img: 'https://flagcdn.com/w320/bv.png',
      region: 'Antarctica',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BR',
      name: 'Brazil',
      code: 'BR',
      img: 'https://flagcdn.com/w320/br.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'IO',
      name: 'British Indian Ocean Territory',
      code: 'IO',
      img: 'https://flagcdn.com/w320/io.png',
      region: 'Indian Ocean',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BN',
      name: 'Brunei Darussalam',
      code: 'BN',
      img: 'https://flagcdn.com/w320/bn.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BG',
      name: 'Bulgaria',
      code: 'BG',
      img: 'https://flagcdn.com/w320/bg.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BF',
      name: 'Burkina Faso',
      code: 'BF',
      img: 'https://flagcdn.com/w320/bf.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BI',
      name: 'Burundi',
      code: 'BI',
      img: 'https://flagcdn.com/w320/bi.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KH',
      name: 'Cambodia',
      code: 'KH',
      img: 'https://flagcdn.com/w320/kh.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CM',
      name: 'Cameroon',
      code: 'CM',
      img: 'https://flagcdn.com/w320/cm.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CA',
      name: 'Canada',
      code: 'CA',
      img: 'https://flagcdn.com/w320/ca.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CV',
      name: 'Cape Verde',
      code: 'CV',
      img: 'https://flagcdn.com/w320/cv.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KY',
      name: 'Cayman Islands',
      code: 'KY',
      img: 'https://flagcdn.com/w320/ky.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CF',
      name: 'Central African Republic',
      code: 'CF',
      img: 'https://flagcdn.com/w320/cf.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TD',
      name: 'Chad',
      code: 'TD',
      img: 'https://flagcdn.com/w320/td.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CL',
      name: 'Chile',
      code: 'CL',
      img: 'https://flagcdn.com/w320/cl.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CN',
      name: 'China',
      code: 'CN',
      img: 'https://flagcdn.com/w320/cn.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CX',
      name: 'Christmas Island',
      code: 'CX',
      img: 'https://flagcdn.com/w320/cx.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CC',
      name: 'Cocos (Keeling) Islands',
      code: 'CC',
      img: 'https://flagcdn.com/w320/cc.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CO',
      name: 'Colombia',
      code: 'CO',
      img: 'https://flagcdn.com/w320/co.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KM',
      name: 'Comoros',
      code: 'KM',
      img: 'https://flagcdn.com/w320/km.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CG',
      name: 'Congo',
      code: 'CG',
      img: 'https://flagcdn.com/w320/cg.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CD',
      name: 'Congo, The Democratic Republic of the',
      code: 'CD',
      img: 'https://flagcdn.com/w320/cd.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CK',
      name: 'Cook Islands',
      code: 'CK',
      img: 'https://flagcdn.com/w320/ck.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CR',
      name: 'Costa Rica',
      code: 'CR',
      img: 'https://flagcdn.com/w320/cr.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'HR',
      name: 'Croatia',
      code: 'HR',
      img: 'https://flagcdn.com/w320/hr.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CU',
      name: 'Cuba',
      code: 'CU',
      img: 'https://flagcdn.com/w320/cu.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CW',
      name: 'Curacao',
      code: 'CW',
      img: 'https://flagcdn.com/w320/cw.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CY',
      name: 'Cyprus',
      code: 'CY',
      img: 'https://flagcdn.com/w320/cy.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CZ',
      name: 'Czech Republic',
      code: 'CZ',
      img: 'https://flagcdn.com/w320/cz.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'DK',
      name: 'Denmark',
      code: 'DK',
      img: 'https://flagcdn.com/w320/dk.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'DJ',
      name: 'Djibouti',
      code: 'DJ',
      img: 'https://flagcdn.com/w320/dj.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'DM',
      name: 'Dominica',
      code: 'DM',
      img: 'https://flagcdn.com/w320/dm.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'DO',
      name: 'Dominican Republic',
      code: 'DO',
      img: 'https://flagcdn.com/w320/do.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'EC',
      name: 'Ecuador',
      code: 'EC',
      img: 'https://flagcdn.com/w320/ec.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'EG',
      name: 'Egypt',
      code: 'EG',
      img: 'https://flagcdn.com/w320/eg.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SV',
      name: 'El Salvador',
      code: 'SV',
      img: 'https://flagcdn.com/w320/sv.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GQ',
      name: 'Equatorial Guinea',
      code: 'GQ',
      img: 'https://flagcdn.com/w320/gq.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'ER',
      name: 'Eritrea',
      code: 'ER',
      img: 'https://flagcdn.com/w320/er.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'EE',
      name: 'Estonia',
      code: 'EE',
      img: 'https://flagcdn.com/w320/ee.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SZ',
      name: 'Eswatini',
      code: 'SZ',
      img: 'https://flagcdn.com/w320/sz.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'ET',
      name: 'Ethiopia',
      code: 'ET',
      img: 'https://flagcdn.com/w320/et.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'FK',
      name: 'Falkland Islands (Malvinas)',
      code: 'FK',
      img: 'https://flagcdn.com/w320/fk.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'FO',
      name: 'Faroe Islands',
      code: 'FO',
      img: 'https://flagcdn.com/w320/fo.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'FJ',
      name: 'Fiji',
      code: 'FJ',
      img: 'https://flagcdn.com/w320/fj.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'FI',
      name: 'Finland',
      code: 'FI',
      img: 'https://flagcdn.com/w320/fi.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'FR',
      name: 'France',
      code: 'FR',
      img: 'https://flagcdn.com/w320/fr.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GF',
      name: 'French Guiana',
      code: 'GF',
      img: 'https://flagcdn.com/w320/gf.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PF',
      name: 'French Polynesia',
      code: 'PF',
      img: 'https://flagcdn.com/w320/pf.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TF',
      name: 'French Southern Territories',
      code: 'TF',
      img: 'https://flagcdn.com/w320/tf.png',
      region: 'Antarctica',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GA',
      name: 'Gabon',
      code: 'GA',
      img: 'https://flagcdn.com/w320/ga.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GM',
      name: 'Gambia',
      code: 'GM',
      img: 'https://flagcdn.com/w320/gm.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GE',
      name: 'Georgia',
      code: 'GE',
      img: 'https://flagcdn.com/w320/ge.png',
      region: 'Eurasia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'DE',
      name: 'Germany',
      code: 'DE',
      img: 'https://flagcdn.com/w320/de.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GH',
      name: 'Ghana',
      code: 'GH',
      img: 'https://flagcdn.com/w320/gh.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GI',
      name: 'Gibraltar',
      code: 'GI',
      img: 'https://flagcdn.com/w320/gi.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GR',
      name: 'Greece',
      code: 'GR',
      img: 'https://flagcdn.com/w320/gr.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GL',
      name: 'Greenland',
      code: 'GL',
      img: 'https://flagcdn.com/w320/gl.png',
      region: 'North America', // geographically part of North America, politically linked to Denmark
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GD',
      name: 'Grenada',
      code: 'GD',
      img: 'https://flagcdn.com/w320/gd.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GP',
      name: 'Guadeloupe',
      code: 'GP',
      img: 'https://flagcdn.com/w320/gp.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GU',
      name: 'Guam',
      code: 'GU',
      img: 'https://flagcdn.com/w320/gu.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GT',
      name: 'Guatemala',
      code: 'GT',
      img: 'https://flagcdn.com/w320/gt.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GG',
      name: 'Guernsey',
      code: 'GG',
      img: 'https://flagcdn.com/w320/gg.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GN',
      name: 'Guinea',
      code: 'GN',
      img: 'https://flagcdn.com/w320/gn.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GW',
      name: 'Guinea-Bissau',
      code: 'GW',
      img: 'https://flagcdn.com/w320/gw.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GY',
      name: 'Guyana',
      code: 'GY',
      img: 'https://flagcdn.com/w320/gy.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'HT',
      name: 'Haiti',
      code: 'HT',
      img: 'https://flagcdn.com/w320/ht.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'HM',
      name: 'Heard Island and Mcdonald Islands',
      code: 'HM',
      img: 'https://flagcdn.com/w320/hm.png',
      region: 'Antarctica',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'VA',
      name: 'Holy See (Vatican City State)',
      code: 'VA',
      img: 'https://flagcdn.com/w320/va.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'HN',
      name: 'Honduras',
      code: 'HN',
      img: 'https://flagcdn.com/w320/hn.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'HK',
      name: 'Hong Kong',
      code: 'HK',
      img: 'https://flagcdn.com/w320/hk.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'HU',
      name: 'Hungary',
      code: 'HU',
      img: 'https://flagcdn.com/w320/hu.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'IS',
      name: 'Iceland',
      code: 'IS',
      img: 'https://flagcdn.com/w320/is.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'IN',
      name: 'India',
      code: 'IN',
      img: 'https://flagcdn.com/w320/in.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'ID',
      name: 'Indonesia',
      code: 'ID',
      img: 'https://flagcdn.com/w320/id.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'IR',
      name: 'Iran, Islamic Republic Of',
      code: 'IR',
      img: 'https://flagcdn.com/w320/ir.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'IQ',
      name: 'Iraq',
      code: 'IQ',
      img: 'https://flagcdn.com/w320/iq.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'IE',
      name: 'Ireland',
      code: 'IE',
      img: 'https://flagcdn.com/w320/ie.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'IM',
      name: 'Isle of Man',
      code: 'IM',
      img: 'https://flagcdn.com/w320/im.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'IL',
      name: 'Israel',
      code: 'IL',
      img: 'https://flagcdn.com/w320/il.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'IT',
      name: 'Italy',
      code: 'IT',
      img: 'https://flagcdn.com/w320/it.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CI',
      name: 'Ivory Coast',
      code: 'CI',
      img: 'https://flagcdn.com/w320/ci.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'JM',
      name: 'Jamaica',
      code: 'JM',
      img: 'https://flagcdn.com/w320/jm.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'JP',
      name: 'Japan',
      code: 'JP',
      img: 'https://flagcdn.com/w320/jp.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'JE',
      name: 'Jersey',
      code: 'JE',
      img: 'https://flagcdn.com/w320/je.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'JO',
      name: 'Jordan',
      code: 'JO',
      img: 'https://flagcdn.com/w320/jo.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KZ',
      name: 'Kazakhstan',
      code: 'KZ',
      img: 'https://flagcdn.com/w320/kz.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KE',
      name: 'Kenya',
      code: 'KE',
      img: 'https://flagcdn.com/w320/ke.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KI',
      name: 'Kiribati',
      code: 'KI',
      img: 'https://flagcdn.com/w320/ki.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KP',
      name: "Korea, Democratic People's Republic of",
      code: 'KP',
      img: 'https://flagcdn.com/w320/kp.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KR',
      name: 'Korea, Republic of',
      code: 'KR',
      img: 'https://flagcdn.com/w320/kr.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KW',
      name: 'Kuwait',
      code: 'KW',
      img: 'https://flagcdn.com/w320/kw.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KG',
      name: 'Kyrgyzstan',
      code: 'KG',
      img: 'https://flagcdn.com/w320/kg.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LA',
      name: 'Lao People\'s Democratic Republic',
      code: 'LA',
      img: 'https://flagcdn.com/w320/la.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LA-2',
      name: 'Laos',
      code: 'LA',
      img: 'https://flagcdn.com/w320/la.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LV',
      name: 'Latvia',
      code: 'LV',
      img: 'https://flagcdn.com/w320/lv.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LB',
      name: 'Lebanon',
      code: 'LB',
      img: 'https://flagcdn.com/w320/lb.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LS',
      name: 'Lesotho',
      code: 'LS',
      img: 'https://flagcdn.com/w320/ls.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LR',
      name: 'Liberia',
      code: 'LR',
      img: 'https://flagcdn.com/w320/lr.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LY',
      name: 'Libyan Arab Jamahiriya',
      code: 'LY',
      img: 'https://flagcdn.com/w320/ly.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LI',
      name: 'Liechtenstein',
      code: 'LI',
      img: 'https://flagcdn.com/w320/li.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LT',
      name: 'Lithuania',
      code: 'LT',
      img: 'https://flagcdn.com/w320/lt.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LU',
      name: 'Luxembourg',
      code: 'LU',
      img: 'https://flagcdn.com/w320/lu.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MO',
      name: 'Macao',
      code: 'MO',
      img: 'https://flagcdn.com/w320/mo.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MK',
      name: 'Macedonia, The Former Yugoslav Republic of',
      code: 'MK',
      img: 'https://flagcdn.com/w320/mk.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MG',
      name: 'Madagascar',
      code: 'MG',
      img: 'https://flagcdn.com/w320/mg.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MW',
      name: 'Malawi',
      code: 'MW',
      img: 'https://flagcdn.com/w320/mw.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MY',
      name: 'Malaysia',
      code: 'MY',
      img: 'https://flagcdn.com/w320/my.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MV',
      name: 'Maldives',
      code: 'MV',
      img: 'https://flagcdn.com/w320/mv.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'ML',
      name: 'Mali',
      code: 'ML',
      img: 'https://flagcdn.com/w320/ml.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MT',
      name: 'Malta',
      code: 'MT',
      img: 'https://flagcdn.com/w320/mt.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MH',
      name: 'Marshall Islands',
      code: 'MH',
      img: 'https://flagcdn.com/w320/mh.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MQ',
      name: 'Martinique',
      code: 'MQ',
      img: 'https://flagcdn.com/w320/mq.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MR',
      name: 'Mauritania',
      code: 'MR',
      img: 'https://flagcdn.com/w320/mr.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MU',
      name: 'Mauritius',
      code: 'MU',
      img: 'https://flagcdn.com/w320/mu.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'YT',
      name: 'Mayotte',
      code: 'YT',
      img: 'https://flagcdn.com/w320/yt.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MX',
      name: 'Mexico',
      code: 'MX',
      img: 'https://flagcdn.com/w320/mx.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'FM',
      name: 'Micronesia, Federated States of',
      code: 'FM',
      img: 'https://flagcdn.com/w320/fm.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MD',
      name: 'Moldova, Republic of',
      code: 'MD',
      img: 'https://flagcdn.com/w320/md.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MC',
      name: 'Monaco',
      code: 'MC',
      img: 'https://flagcdn.com/w320/mc.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MN',
      name: 'Mongolia',
      code: 'MN',
      img: 'https://flagcdn.com/w320/mn.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'ME',
      name: 'Montenegro',
      code: 'ME',
      img: 'https://flagcdn.com/w320/me.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MS',
      name: 'Montserrat',
      code: 'MS',
      img: 'https://flagcdn.com/w320/ms.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MA',
      name: 'Morocco',
      code: 'MA',
      img: 'https://flagcdn.com/w320/ma.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MZ',
      name: 'Mozambique',
      code: 'MZ',
      img: 'https://flagcdn.com/w320/mz.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MM',
      name: 'Myanmar',
      code: 'MM',
      img: 'https://flagcdn.com/w320/mm.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NA',
      name: 'Namibia',
      code: 'NA',
      img: 'https://flagcdn.com/w320/na.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NR',
      name: 'Nauru',
      code: 'NR',
      img: 'https://flagcdn.com/w320/nr.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NP',
      name: 'Nepal',
      code: 'NP',
      img: 'https://flagcdn.com/w320/np.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NL',
      name: 'Netherlands',
      code: 'NL',
      img: 'https://flagcdn.com/w320/nl.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AN',
      name: 'Netherlands Antilles',
      code: 'AN',
      img: 'https://flagcdn.com/w320/an.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NC',
      name: 'New Caledonia',
      code: 'NC',
      img: 'https://flagcdn.com/w320/nc.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NZ',
      name: 'New Zealand',
      code: 'NZ',
      img: 'https://flagcdn.com/w320/nz.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NI',
      name: 'Nicaragua',
      code: 'NI',
      img: 'https://flagcdn.com/w320/ni.png',
      region: 'Central America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NE',
      name: 'Niger',
      code: 'NE',
      img: 'https://flagcdn.com/w320/ne.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NG',
      name: 'Nigeria',
      code: 'NG',
      img: 'https://flagcdn.com/w320/ng.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NU',
      name: 'Niue',
      code: 'NU',
      img: 'https://flagcdn.com/w320/nu.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NF',
      name: 'Norfolk Island',
      code: 'NF',
      img: 'https://flagcdn.com/w320/nf.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MP',
      name: 'Northern Mariana Islands',
      code: 'MP',
      img: 'https://flagcdn.com/w320/mp.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'NO',
      name: 'Norway',
      code: 'NO',
      img: 'https://flagcdn.com/w320/no.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'OM',
      name: 'Oman',
      code: 'OM',
      img: 'https://flagcdn.com/w320/om.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PK',
      name: 'Pakistan',
      code: 'PK',
      img: 'https://flagcdn.com/w320/pk.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PW',
      name: 'Palau',
      code: 'PW',
      img: 'https://flagcdn.com/w320/pw.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PS',
      name: 'Palestinian Territory, Occupied',
      code: 'PS',
      img: 'https://flagcdn.com/w320/ps.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PA',
      name: 'Panama',
      code: 'PA',
      img: 'https://flagcdn.com/w320/pa.png',
      region: 'Central America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PG',
      name: 'Papua New Guinea',
      code: 'PG',
      img: 'https://flagcdn.com/w320/pg.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PY',
      name: 'Paraguay',
      code: 'PY',
      img: 'https://flagcdn.com/w320/py.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PE',
      name: 'Peru',
      code: 'PE',
      img: 'https://flagcdn.com/w320/pe.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PH',
      name: 'Philippines',
      code: 'PH',
      img: 'https://flagcdn.com/w320/ph.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PN',
      name: 'Pitcairn',
      code: 'PN',
      img: 'https://flagcdn.com/w320/pn.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PL',
      name: 'Poland',
      code: 'PL',
      img: 'https://flagcdn.com/w320/pl.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PT',
      name: 'Portugal',
      code: 'PT',
      img: 'https://flagcdn.com/w320/pt.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PR',
      name: 'Puerto Rico',
      code: 'PR',
      img: 'https://flagcdn.com/w320/pr.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'QA',
      name: 'Qatar',
      code: 'QA',
      img: 'https://flagcdn.com/w320/qa.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'RW',
      name: 'RWANDA',
      code: 'RW',
      img: 'https://flagcdn.com/w320/rw.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'RE',
      name: 'Reunion',
      code: 'RE',
      img: 'https://flagcdn.com/w320/re.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'RO',
      name: 'Romania',
      code: 'RO',
      img: 'https://flagcdn.com/w320/ro.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'RU',
      name: 'Russian Federation',
      code: 'RU',
      img: 'https://flagcdn.com/w320/ru.png',
      region: 'Europe/Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'BL',
      name: 'Saint Barthelemy',
      code: 'BL',
      img: 'https://flagcdn.com/w320/bl.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SH',
      name: 'Saint Helena',
      code: 'SH',
      img: 'https://flagcdn.com/w320/sh.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'KN',
      name: 'Saint Kitts and Nevis',
      code: 'KN',
      img: 'https://flagcdn.com/w320/kn.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LC',
      name: 'Saint Lucia',
      code: 'LC',
      img: 'https://flagcdn.com/w320/lc.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'MF',
      name: 'Saint Martin',
      code: 'MF',
      img: 'https://flagcdn.com/w320/mf.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'PM',
      name: 'Saint Pierre and Miquelon',
      code: 'PM',
      img: 'https://flagcdn.com/w320/pm.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'VC',
      name: 'Saint Vincent and the Grenadines',
      code: 'VC',
      img: 'https://flagcdn.com/w320/vc.png',
      region: 'Caribbean',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'WS',
      name: 'Samoa',
      code: 'WS',
      img: 'https://flagcdn.com/w320/ws.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SM',
      name: 'San Marino',
      code: 'SM',
      img: 'https://flagcdn.com/w320/sm.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'ST',
      name: 'Sao Tome and Principe',
      code: 'ST',
      img: 'https://flagcdn.com/w320/st.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SA',
      name: 'Saudi Arabia',
      code: 'SA',
      img: 'https://flagcdn.com/w320/sa.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SN',
      name: 'Senegal',
      code: 'SN',
      img: 'https://flagcdn.com/w320/sn.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'RS',
      name: 'Serbia',
      code: 'RS',
      img: 'https://flagcdn.com/w320/rs.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SC',
      name: 'Seychelles',
      code: 'SC',
      img: 'https://flagcdn.com/w320/sc.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SL',
      name: 'Sierra Leone',
      code: 'SL',
      img: 'https://flagcdn.com/w320/sl.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SG',
      name: 'Singapore',
      code: 'SG',
      img: 'https://flagcdn.com/w320/sg.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SX',
      name: 'Sint Maarten',
      code: 'SX',
      img: 'https://flagcdn.com/w320/sx.png',
      region: 'Caribbean',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SK',
      name: 'Slovakia',
      code: 'SK',
      img: 'https://flagcdn.com/w320/sk.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SI',
      name: 'Slovenia',
      code: 'SI',
      img: 'https://flagcdn.com/w320/si.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SB',
      name: 'Solomon Islands',
      code: 'SB',
      img: 'https://flagcdn.com/w320/sb.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SO',
      name: 'Somalia',
      code: 'SO',
      img: 'https://flagcdn.com/w320/so.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'ZA',
      name: 'South Africa',
      code: 'ZA',
      img: 'https://flagcdn.com/w320/za.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GS',
      name: 'South Georgia and the South Sandwich Islands',
      code: 'GS',
      img: 'https://flagcdn.com/w320/gs.png',
      region: 'Antarctica',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SS',
      name: 'South Sudan',
      code: 'SS',
      img: 'https://flagcdn.com/w320/ss.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'ES',
      name: 'Spain',
      code: 'ES',
      img: 'https://flagcdn.com/w320/es.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'LK',
      name: 'Sri Lanka',
      code: 'LK',
      img: 'https://flagcdn.com/w320/lk.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SD',
      name: 'Sudan',
      code: 'SD',
      img: 'https://flagcdn.com/w320/sd.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SR',
      name: 'Suriname',
      code: 'SR',
      img: 'https://flagcdn.com/w320/sr.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SJ',
      name: 'Svalbard and Jan Mayen',
      code: 'SJ',
      img: 'https://flagcdn.com/w320/sj.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SE',
      name: 'Sweden',
      code: 'SE',
      img: 'https://flagcdn.com/w320/se.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'CH',
      name: 'Switzerland',
      code: 'CH',
      img: 'https://flagcdn.com/w320/ch.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'SY',
      name: 'Syrian Arab Republic',
      code: 'SY',
      img: 'https://flagcdn.com/w320/sy.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TW',
      name: 'Taiwan',
      code: 'TW',
      img: 'https://flagcdn.com/w320/tw.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TJ',
      name: 'Tajikistan',
      code: 'TJ',
      img: 'https://flagcdn.com/w320/tj.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TZ',
      name: 'Tanzania, United Republic of',
      code: 'TZ',
      img: 'https://flagcdn.com/w320/tz.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TH',
      name: 'Thailand',
      code: 'TH',
      img: 'https://flagcdn.com/w320/th.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TL',
      name: 'Timor-Leste',
      code: 'TL',
      img: 'https://flagcdn.com/w320/tl.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TG',
      name: 'Togo',
      code: 'TG',
      img: 'https://flagcdn.com/w320/tg.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TK',
      name: 'Tokelau',
      code: 'TK',
      img: 'https://flagcdn.com/w320/tk.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TO',
      name: 'Tonga',
      code: 'TO',
      img: 'https://flagcdn.com/w320/to.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TT',
      name: 'Trinidad and Tobago',
      code: 'TT',
      img: 'https://flagcdn.com/w320/tt.png',
      region: 'Caribbean',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TN',
      name: 'Tunisia',
      code: 'TN',
      img: 'https://flagcdn.com/w320/tn.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TR',
      name: 'Turkey',
      code: 'TR',
      img: 'https://flagcdn.com/w320/tr.png',
      region: 'Europe/Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TM',
      name: 'Turkmenistan',
      code: 'TM',
      img: 'https://flagcdn.com/w320/tm.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TC',
      name: 'Turks and Caicos Islands',
      code: 'TC',
      img: 'https://flagcdn.com/w320/tc.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'TV',
      name: 'Tuvalu',
      code: 'TV',
      img: 'https://flagcdn.com/w320/tv.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'UG',
      name: 'Uganda',
      code: 'UG',
      img: 'https://flagcdn.com/w320/ug.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'UA',
      name: 'Ukraine',
      code: 'UA',
      img: 'https://flagcdn.com/w320/ua.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AE',
      name: 'United Arab Emirates',
      code: 'AE',
      img: 'https://flagcdn.com/w320/ae.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'GB',
      name: 'United Kingdom',
      code: 'GB',
      img: 'https://flagcdn.com/w320/gb.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'US',
      name: 'United States',
      code: 'US',
      img: 'https://flagcdn.com/w320/us.png',
      region: 'North America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'UM',
      name: 'United States Minor Outlying Islands',
      code: 'UM',
      img: 'https://flagcdn.com/w320/um.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'UY',
      name: 'Uruguay',
      code: 'UY',
      img: 'https://flagcdn.com/w320/uy.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'UZ',
      name: 'Uzbekistan',
      code: 'UZ',
      img: 'https://flagcdn.com/w320/uz.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'VU',
      name: 'Vanuatu',
      code: 'VU',
      img: 'https://flagcdn.com/w320/vu.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'VE',
      name: 'Venezuela',
      code: 'VE',
      img: 'https://flagcdn.com/w320/ve.png',
      region: 'South America',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'VN',
      name: 'Vietnam',
      code: 'VN',
      img: 'https://flagcdn.com/w320/vn.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'VG',
      name: 'Virgin Islands, British',
      code: 'VG',
      img: 'https://flagcdn.com/w320/vg.png',
      region: 'Caribbean',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'VI',
      name: 'Virgin Islands, U.S.',
      code: 'VI',
      img: 'https://flagcdn.com/w320/vi.png',
      region: 'Caribbean',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'WF',
      name: 'Wallis and Futuna',
      code: 'WF',
      img: 'https://flagcdn.com/w320/wf.png',
      region: 'Oceania',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'EH',
      name: 'Western Sahara',
      code: 'EH',
      img: 'https://flagcdn.com/w320/eh.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'YE',
      name: 'Yemen',
      code: 'YE',
      img: 'https://flagcdn.com/w320/ye.png',
      region: 'Asia',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'ZM',
      name: 'Zambia',
      code: 'ZM',
      img: 'https://flagcdn.com/w320/zm.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'ZW',
      name: 'Zimbabwe',
      code: 'ZW',
      img: 'https://flagcdn.com/w320/zw.png',
      region: 'Africa',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    },
    {
      id: 'AX',
      name: 'Åland Islands',
      code: 'AX',
      img: 'https://flagcdn.com/w320/ax.png',
      region: 'Europe',
      coverage: '4G/LTE/5G',
      plans: 0,
      popular: false,
      lowerPrice: 0,
    }
]

export default function Countries() {
    const [searchQuery, setSearchQuery] = useState('');
  const [selectedRegion, setSelectedRegion] = useState('Бүгд');
  const [filteredCountries, setFilteredCountries] = useState(countries);

  const getCountryFlagUrl = (countryName) => {
  const found = countries.find(
    (c) => c.name.toLowerCase() === countryName.toLowerCase()
  );
  // Return the found image URL, or a fallback image if not found.
  return found ? found.img : '/default-flag.png';
}


  return (
    <div className='flex min-h-screen flex-col'>
      <main className='flex-1'>
        {/* Hero Section */}
        <section className='w-full py-8 md:py-12 bg-muted'>
          <div className='container mx-auto px-4 md:px-6'>
            <div className='flex flex-col items-center text-center space-y-4'>
              <h1 className='text-3xl font-bold'>eSIM дата багцууд (Улсаар)</h1>
              <p className='max-w-[700px] text-muted-foreground md:text-xl'>
                190+ гаруй улсын дата багцуудаас сонголтоо хийгээрэй
              </p>
            </div>
          </div>
        </section>

        {/* Search and Filter Section */}
        <section className='w-full py-6 border-b'>
          <div className='container mx-auto px-4 md:px-6'>
            <div className='flex flex-col sm:flex-row gap-4 items-center justify-between'>
              <div className='flex flex-col sm:flex-row gap-4 w-full sm:w-auto'>
                <div className='relative w-full sm:w-[300px]'>
                  <Search className='absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground' />
                  <Input
                    type='search'
                    placeholder='Улсаар хайх...'
                    className='w-full pl-8'
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                  />
                </div>
                <Select
                  value={selectedRegion}
                  onValueChange={setSelectedRegion}
                >
                  <SelectTrigger className='w-full sm:w-[180px]'>
                    <SelectValue placeholder='Select region' />
                  </SelectTrigger>
                  <SelectContent>
                    {regions.map((region) => (
                      <SelectItem key={region} value={region}>
                        {region}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              {(searchQuery || selectedRegion !== 'Бүгд') && (
                <Button
                  variant='ghost'
                  size='sm'
                  className='h-9'
                  onClick={clearFilters}
                >
                  <X className='mr-2 h-4 w-4' />
                  Цэвэрлэх
                </Button>
              )}
            </div>
          </div>
        </section>

        {/* Countries List Section */}
        <section className='w-full py-8 md:py-12'>
          <div className='container mx-auto px-4 md:px-6'>
            <Tabs defaultValue='grid' className='w-full'>
              <div className='flex justify-between items-center mb-6'>
                <h2 className='text-2xl font-bold'>
                  {filteredCountries.length} улс олдлоо
                </h2>
                <TabsList>
                  <TabsTrigger value='grid'>Хүснэгтээр</TabsTrigger>
                  <TabsTrigger value='list'>Жагсаалтаар</TabsTrigger>
                </TabsList>
              </div>

              {/* Grid View */}
              <TabsContent value='grid' className='space-y-4'>
                {filteredCountries.length === 0 ? (
                  <div className='text-center py-12'>
                    <Globe className='h-12 w-12 mx-auto text-muted-foreground mb-4' />
                    <h3 className='text-lg font-medium'>Хайлт илэрцгүй</h3>
                    <p className='text-muted-foreground mt-2'>
                      Өөрөөр хайгаад үзээрэй
                    </p>
                    <Button
                      variant='outline'
                      className='mt-4'
                      onClick={clearFilters}
                    >
                      Цэвэрлэх
                    </Button>
                  </div>
                ) : (
                  <div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6'>
                    {filteredCountries.map((country) => (
                      <Link href={`/countries/${country.id}`} key={country.id}>
                        <Card className='overflow-hidden h-full transition-all hover:border-primary hover:shadow-md'>
                          <CardContent className=''>
                            <div className='relative h-40 w-full bg-muted px-12 border'>
                              <figure className='px-12 h-[1px] w-[250px]'>
                                <Image
                                  src={country.img}
                                  alt={`${country.name} Flag`}
                                  fill
                                  className=''
                                />
                              </figure>
                              {country.popular && (
                                <Badge className='absolute top-2 right-2'>
                                  Эрэлттэй
                                </Badge>
                              )}
                            </div>
                            <div className='py-4'>
                              <div className='flex justify-between items-start mb-2'>
                                <h3 className='font-bold'>{country.name}</h3>
                                <ChevronRight className='h-5 w-5 text-muted-foreground' />
                              </div>
                              <div className='flex items-center gap-1 text-sm text-muted-foreground mb-1'>
                                <Globe className='h-4 w-4' />
                                <span>{country.region}</span>
                              </div>
                              <div className='flex items-center gap-1 text-sm text-muted-foreground'>
                                <MapPin className='h-4 w-4' />
                                <span>{country.coverage} сүлжээ</span>
                              </div>
                              <div className='mt-3 flex justify-between items-center'>
                                <span className='text-sm font-medium'>
                                  {country.plans} боломжит багц
                                </span>
                                <span className='text-sm'>
                                  {country.lowerPrice} ТӨГ
                                </span>
                              </div>
                            </div>
                          </CardContent>
                        </Card>
                      </Link>
                    ))}
                  </div>
                )}
              </TabsContent>

              {/* List View */}
              <TabsContent value='list' className='space-y-4'>
                {filteredCountries.length === 0 ? (
                  <div className='text-center py-12'>
                    <Globe className='h-12 w-12 mx-auto text-muted-foreground mb-4' />
                    <h3 className='text-lg font-medium'>Хайлт илэрцгүй</h3>
                    <p className='text-muted-foreground mt-2'>
                      Өөрөөр хайгаад үзээрэй
                    </p>
                    <Button
                      variant='outline'
                      className='mt-4'
                      onClick={clearFilters}
                    >
                      Цэвэрлэх
                    </Button>
                  </div>
                ) : (
                  <div className='rounded-lg border overflow-hidden'>
                    <div className='hidden md:grid md:grid-cols-5 bg-muted px-4 py-3 font-medium text-sm'>
                      <div className='col-span-2'>Улс</div>
                      <div>Бүс</div>
                      <div>Сүлжээ</div>
                      <div className='text-right'>Үнэ</div>
                    </div>
                    <div className='divide-y'>
                      {filteredCountries.map((country) => (
                        <Link
                          href={`/countries/${country.id}`}
                          key={country.id}
                          className='block hover:bg-muted/50'
                        >
                          <div className='p-4'>
                            <div className='md:grid md:grid-cols-5 md:items-center gap-4'>
                              <div className='col-span-2 flex items-center gap-3 mb-2 md:mb-0'>
                                <div className='relative h-10 w-16 flex-shrink-0 bg-muted overflow-hidden rounded border'>
                                  <Image
                                    src={
                                      getCountryFlagUrl(country.id) ||
                                      '/placeholder.svg'
                                    }
                                    alt={`${country.name} Flag`}
                                    fill
                                    className='object-cover'
                                  />
                                </div>
                                <div>
                                  <div className='flex items-center gap-2'>
                                    <h3 className='font-medium'>
                                      {country.name}
                                    </h3>
                                    {country.popular && (
                                      <Badge
                                        variant='outline'
                                        className='text-xs'
                                      >
                                        Эрэлттэй
                                      </Badge>
                                    )}
                                  </div>
                                  <p className='text-sm text-muted-foreground md:hidden'>
                                    {country.region}
                                  </p>
                                </div>
                              </div>
                              <div className='hidden md:block'>
                                <span>{country.region}</span>
                              </div>
                              <div className='flex md:block items-center justify-between mb-2 md:mb-0'>
                                <span className='text-sm md:text-base'>
                                  {country.coverage}
                                </span>
                                <span className='md:hidden text-sm text-muted-foreground'>
                                  {country.plans} багцууд
                                </span>
                              </div>
                              <div className='flex md:block items-center justify-between md:text-right'>
                                <span className='text-sm md:text-base'>
                                  {country.lowerPrice} ТӨГ
                                </span>
                                <ChevronRight className='h-5 w-5 text-muted-foreground md:hidden' />
                              </div>
                            </div>
                          </div>
                        </Link>
                      ))}
                    </div>
                  </div>
                )}
              </TabsContent>
            </Tabs>
          </div>
        </section>

        {/* Popular Regions Section */}
        <section className='w-full py-8 md:py-12 bg-muted'>
          <div className='container mx-auto px-4 md:px-6'>
            <div className='flex flex-col items-center justify-center space-y-4 text-center mb-8'>
              <h2 className='text-2xl font-bold'>Бүс нутгаар хайх</h2>
              <p className='max-w-[700px] text-muted-foreground'>
                Тив эсвэл бүх нутгаар хайгаад үзээрэй
              </p>
            </div>

            <div className='grid grid-cols-2 md:grid-cols-4 gap-4'>
              {regions
                .filter((r) => r !== 'Бүгд')
                .map((region) => (
                  <Card
                    key={region}
                    className='overflow-hidden cursor-pointer hover:border-primary transition-colors'
                    onClick={() => {
                      setSelectedRegion(region);
                      window.scrollTo({ top: 0, behavior: 'smooth' });
                    }}
                  >
                    <CardContent className='p-6 flex flex-col items-center text-center'>
                      <Globe className='h-8 w-8 mb-3 text-primary' />
                      <h3 className='font-bold'>{region}</h3>
                      <p className='text-sm text-muted-foreground mt-1'>
                        {countries.filter((c) => c.region === region).length}{' '}
                        улс
                      </p>
                    </CardContent>
                  </Card>
                ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className='w-full py-8 md:py-12 bg-primary text-primary-foreground'>
          <div className='container mx-auto px-4 md:px-6'>
            <div className='flex flex-col items-center justify-center space-y-4 text-center'>
              <div className='space-y-2'>
                <h2 className='text-2xl font-bold'>
                  Худалдаж авахад бэлэн үү?
                </h2>
                <p className='max-w-[700px]'>
                  Аялах газраа сонгоод eSIM ээ аваарай
                </p>
              </div>
              <div className='flex flex-col gap-2 min-[400px]:flex-row'>
                <Button size='lg' variant='secondary' asChild>
                  <Link href='#top'>Багц сонирхох</Link>
                </Button>
                <Button
                  size='lg'
                  variant='outline'
                  className='bg-transparent text-primary-foreground border-primary-foreground hover:bg-primary-foreground/10'
                  asChild
                >
                  <Link href='/contact'>Асуулт байна?</Link>
                </Button>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
